name-template: PWA Expert System $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION

categories:
  - title: 💡 New features
    label: 💡 Enhancement
  - title: 🐛 Bug fixes
    label: Bug
  - title: 🔨 Interface changes
    label: 🔨 Maintenance
  - title: 📝 Documentation
    label: 📝 Docs
  - title: 🖱️ Internals
    label: 🖱️ DX

change-template: "- $TITLE (#$NUMBER)"
sort-direction: ascending
template: |
  # Release $NEXT_PATCH_VERSION

  $CHANGES

  ## Contributors since [$PREVIOUS_TAG](https://github.com/ComPWA/expertsystem/releases/tag/$PREVIOUS_TAG)

  $CONTRIBUTORS
