tasks:
  - init: pip install -c .constraints/py3.8.txt -e .[dev]

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addComment: false
    addBadge: false
    addLabel: false

vscode:
  extensions:
    - bungcip.better-toml
    - christian-kohler.path-intellisense
    - davidanson.vscode-markdownlint
    - eamodio.gitlens
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - executablebookproject.myst-highlight
    - github.vscode-pull-request-github
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-vsliveshare.vsliveshare
    - redhat.vscode-yaml
    - ryanluker.vscode-coverage-gutters
    - stkb.rewrap
    - streetsidesoftware.code-spell-checker
    - travisillig.vscode-json-stable-stringify
    - tyriar.sort-lines
    - yzhang.markdown-all-in-one
