tasks:
  - init: pip install -r reqs/3.8/requirements-dev.txt -e .

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addComment: false
    addBadge: false
    addLabel: false
