version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - htmlzip

python:
  version: 3.7
  install:
    - requirements: .reqs/doc.txt
    - method: pip
      path: .
