version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - |-
      export PIXI_HOME=$READTHEDOCS_VIRTUALENV_PATH
      curl -fsSL https://pixi.sh/install.sh | bash
      pixi global install graphviz uv
    - |-
      export UV_LINK_MODE=copy
      uv run \
        --group doc \
        --locked \
        --no-dev \
        --with tox \
        tox -e doc
      mkdir -p $READTHEDOCS_OUTPUT
      mv docs/_build/html $READTHEDOCS_OUTPUT
