version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - htmlzip

python:
  version: "3.8"
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
