version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - htmlzip

python:
  version: 3.8
  install:
    - requirements: reqs/3.8/requirements-doc.txt
    - method: pip
      path: .
