version: 2

sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: true

formats:
  - htmlzip

python:
  version: 3.7
  install:
    - requirements: requirements.txt
    - requirements: doc/requirements.txt
    - method: setuptools
      path: .
