version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
  jobs:
    post_install:
      - python -m pip install 'uv>=0.2.0'
      - python -m uv sync --extra=doc
formats:
  - htmlzip

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
