exclude = [
    "**/Cargo.toml",
    "**/Manifest.toml",
    "**/Project.toml",
    "labels*.toml",
]

[formatting]
align_entries = false
array_auto_collapse = false
array_auto_expand = true
array_trailing_comma = true
column_width = 88
indent_string = "    "
reorder_arrays = true
reorder_keys = true
