name: ampform
channels:
  - defaults
dependencies:
  - python==3.11.*
  - pip
  - graphviz
  - pip:
      - -c .constraints/py3.11.txt -e .[dev]
variables:
  PYDEVD_DISABLE_FILE_VALIDATION: 1
  PYTHONHASHSEED: 0
