name: ampform
channels:
  - defaults
dependencies:
  - python==3.11.*
  - pip
  - graphviz # for binder
  - pip:
      - -c .constraints/py3.11.txt -e .[dev]
variables:
  PRETTIER_LEGACY_CLI: "1"
  PYTHONHASHSEED: 0
