#!/bin/bash
set -ex
curl -LsSf https://astral.sh/uv/install.sh | sh
source $HOME/.cargo/env
uv export \
  --extra jupyter \
  --extra notebooks \
  > requirements.txt
uv pip install \
  --requirement requirements.txt \
  --system
uv cache clean
