name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: |-
    ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}

on:
  push:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  pull_request:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:

jobs:
  doc:
    uses: ComPWA/actions/.github/workflows/ci-docs.yml@e9e39f6b4e489f783fbeb9c0a8ed5992faa1f027 # v4.1.3
    permissions:
      pages: write
      id-token: write
  style:
    secrets:
      token: ${{ secrets.PAT }}
    uses: ComPWA/actions/.github/workflows/style.yml@e9e39f6b4e489f783fbeb9c0a8ed5992faa1f027 # v4.1.3
  test:
    uses: ComPWA/actions/.github/workflows/test.yml@e9e39f6b4e489f783fbeb9c0a8ed5992faa1f027 # v4.1.3
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      coverage-python-version: "3.14"
      macos-python-version: "3.11"
