name: Clean caches

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      ref:
        description: Clean caches for this branch name or ref
        required: false
        type: string

jobs:
  cleanup:
    name: Remove caches
    runs-on: ubuntu-22.04
    steps:
      - uses: ComPWA/actions/clean-caches@v1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ inputs.ref }}
