name: Clean caches

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      ref:
        description: Clean caches for this branch name or ref
        required: false
        type: string

jobs:
  cleanup:
    name: Remove caches
    runs-on: ubuntu-slim
    steps:
      - uses: ComPWA/actions/clean-caches@957d1151460aea469a230150b61cc3c99d3f0a0a # 4.1.2
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ inputs.ref }}
