name: Clean caches

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  cleanup:
    name: Remove caches
    runs-on: ubuntu-22.04
    steps:
      - uses: ComPWA/actions/clean-caches@v1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
