name: PR linting
on:
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - reopened
      - synchronize
      - unlabeled

jobs:
  lint-pr:
    uses: ComPWA/actions/.github/workflows/pr-linting.yml@957d1151460aea469a230150b61cc3c99d3f0a0a # 4.1.2
